@startuml
skinparam style strictuml
|PlanETS (SMS)|
start
:Update weight of assignment
(if needed);
|Moodle (LMS)|
:Update weight, name, contents,
dates, etc. of assignment;
|SIGNETS (GMS)|
:Update weight, name, contents,
dates, etc. of assignment;
stop
@enduml
