@startuml
skinparam style strictuml
|<img:https://planets.etsmtl.ca/App_Themes/ApplicationTheme/Images/logo_planETS.png>|
start
:Update weight of assignment
(if needed);
|<img:http://www.taotesting.com/wp-content/uploads/2014/09/moodle-logo.jpg>|
:Update weight, name, contents,
dates, etc. of assignment;
|<img:https://signets.etsmtl.ca/App_Themes/ApplicationTheme/Images/logo_app.png>|
:Update weight, name, contents,
dates, etc. of assignment;
stop
@enduml
