@startuml
SkinParam style strictuml
actor ":Teacher" as T
participant ":System" as S
T -> S: Send MBZ file and ICS url
S -> T: Return transaction id (cookies)

loop while no confirmation
    T -> S: Send text planning with transaction id (cookies)
    T <- S: Return preview as a json representation of the calendar
end

T -> S: Send text planning with transaction id (cookies) with confirmation
T <- S: Return the new moodle archive
@enduml
